// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/LyricTian/gin-admin/v6/internal/app/api"
	"github.com/LyricTian/gin-admin/v6/internal/app/bll/impl/bll"
	"github.com/LyricTian/gin-admin/v6/internal/app/model/impl/gorm/model"
	"github.com/LyricTian/gin-admin/v6/internal/app/module/adapter"
	"github.com/LyricTian/gin-admin/v6/internal/app/router"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	auther, cleanup, err := InitAuth()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := InitGormDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	app := &model.App{
		DB: db,
	}
	role := &model.Role{
		DB: db,
	}
	resource := &model.Resource{
		DB: db,
	}
	roleResource := &model.RoleResource{
		DB: db,
	}
	account := &model.Account{
		DB: db,
	}
	accountSystem := &model.AccountSystem{
		DB: db,
	}
	accountRole := &model.AccountRole{
		DB: db,
	}
	trans := &model.Trans{
		DB: db,
	}

	casbinAdapter := &adapter.CasbinAdapter{
		AccountModel:      	account,
		RoleModel:         	role,
		ResourceModel: 		resource,
		AccountRoleModel:  	accountRole,
		RoleResourceModel:	roleResource,
	}
	syncedEnforcer, cleanup3, err := InitCasbin(casbinAdapter)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}

	// bll
	bllAccount := &bll.Account{
		Enforcer:			syncedEnforcer,
		TransModel:    		trans,
		AccountModel:     	account,
		AccountSystemModel: accountSystem,
		AccountRoleModel: 	accountRole,
		RoleModel:			role,
	}

	bllLogin := &bll.Login{
		Enforcer:			syncedEnforcer,
		Auth:            	auther,
		AppModel:			app,
		AccountModel:     	account,
		AccountRoleModel: 	accountRole,
		RoleModel:       	role,
		RoleResourceModel:  roleResource,
		ResourceModel:      resource,
	}

	bllResource := &bll.Resource{
		TransModel:    		trans,
		ResourceModel:      resource,
	}

	bllApp := &bll.App{
		AppModel:        	app,
	}

	//bllRole := &bll.Role{
	//	Enforcer:      syncedEnforcer,
	//	TransModel:    trans,
	//	RoleModel:     role,
	//	RoleMenuModel: roleMenu,
	//	UserModel:     user,
	//}
	//
	//bllUser := &bll.User{
	//	Enforcer:      syncedEnforcer,
	//	TransModel:    trans,
	//	UserModel:     user,
	//	UserRoleModel: userRole,
	//	RoleModel:     role,
	//}

	// api
	apiAccount := &api.Account{
		AccountBll: bllAccount,
	}

	apiLogin := &api.Login{
		LoginBll: bllLogin,
		AppBll: bllApp,
	}

	//apiMenu := &api.Menu{
	//	MenuBll: bllMenu,
	//}
	//
	//apiRole := &api.Role{
	//	RoleBll: bllRole,
	//}
	//
	//apiUser := &api.Account{
	//	UserBll: bllUser,
	//}

	// router
	routerRouter := &router.Router{
		Auth:           auther,
		CasbinEnforcer: syncedEnforcer,
		LoginAPI:       apiLogin,
		AccountAPI:     apiAccount,
	}

	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine:         engine,
		Auth:           auther,
		CasbinEnforcer: syncedEnforcer,
		ResourceBll: 	bllResource,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
